---
server:
    install: '1'
    packages: [vim, git, fail2ban]
    timezone: America/Sao_Paulo
    locale: pt_BR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: '', useVagrantCloud: '1', syncType: '0' }
nginx:
    install: '1'
    docroot: /vagrant
    servername: inscricao.dev
mysql:
    install: '1'
    root_password: root
    database: inscricao
    user: inscricao
    password: inscricao2015
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-gd, php5-curl, php5-common, php5-mysql, php5-xdebug, php5-fpm]

